import { Select } from '@geist-ui/core'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {

  const selectHandler = (e) => {

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <h1 className={styles.title}>
            Chamada <a href="#">Salesiano</a>
          </h1>

          <p className={styles.description}>
            Projeto Teste  
          </p>
          
        </div>
      </main>


    </div>
  )
}
